### ISSUE TITLE
Plugin "browser_detect" missing, maybe you need to install it?

### ISSUE THREAD

**Issue by moschlar** [derf/vrr-fakedisplay#1]
Hi,

when I try to follow your instructions on Debian Buster, I just get the following error message when I try to start the server:
`Plugin "browser_detect" missing, maybe you need to install it?`

What am I doing wrong?

**Comment by derf** [comment]
Technically nothing, that's a mistake on my side. I forgot to mention the dependency `Mojolicious::Plugin::BrowserDetect` in the README, once you have installed it from CPAN you should be fine.

It's not available as a Debian package unfortunately.

I'll update the README and add a cpanfile suitable for automatic dependency installation using cpanminus later today.

**Comment by moschlar** [comment]
Great, thanks!
